drop table IF EXISTS "DOCTOR_DETAILS";
drop table IF EXISTS "CUSTOMER";
drop table IF EXISTS "HOSPITAL";

drop table IF EXISTS "CUSTOMER_FOLLOWUP_NOTIFICATION";

CREATE TABLE CUSTOMER (
    CUSTOMER_ID INTEGER NOT NULL AUTO_INCREMENT,
    CUSTOMER_NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(50),
    PHONE_NUMBER VARCHAR(10) NOT NULL UNIQUE,
    PRIMARY KEY (CUSTOMER_ID)
);

CREATE TABLE HOSPITAL (
    HOSPITAL_ID INTEGER NOT NULL AUTO_INCREMENT,
    HOSPITAL_NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    PHONE_NUMBER VARCHAR(10) NOT NULL,
    SPECIALIZATION VARCHAR(250) NOT NULL,
    LOCATION VARCHAR(250) NOT NULL,
    PRIMARY KEY (HOSPITAL_ID)
);

CREATE TABLE DOCTOR_DETAILS (
    DOCTOR_ID INTEGER NOT NULL AUTO_INCREMENT,
    DOCTOR_NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    PHONE_NUMBER VARCHAR(10) NOT NULL,
    SPECIALIZATION VARCHAR(250) NOT NULL,
    LOCATION VARCHAR(250) NOT NULL,
    HOSPITAL_ID INTEGER,
    PRIMARY KEY (DOCTOR_ID),
    FOREIGN KEY (HOSPITAL_ID) REFERENCES HOSPITAL(HOSPITAL_ID)
);


CREATE TABLE CUSTOMER_FOLLOWUP_NOTIFICATION (
    NOTIFICATION_ID INTEGER NOT NULL AUTO_INCREMENT,
    CUSTOMER_ID INTEGER NOT NULL,
    DOCTOR_ID INTEGER NOT NULL,
    FOLLOW_UP_DATE TIMESTAMP,
    PRIMARY KEY (NOTIFICATION_ID),
    FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
    FOREIGN KEY(DOCTOR_ID) REFERENCES DOCTOR_DETAILS(DOCTOR_ID)
);




insert into CUSTOMER(CUSTOMER_NAME, EMAIL, PHONE_NUMBER)
VALUES('Venkata Chinni','test@gmail.com','1234567890');

insert into CUSTOMER(CUSTOMER_NAME, EMAIL, PHONE_NUMBER)
VALUES('Purushotham T','test@gmail.com','1234567809');

insert into HOSPITAL(HOSPITAL_NAME, EMAIL, PHONE_NUMBER, SPECIALIZATION, LOCATION)
VALUES('HIMAGIRI Hospitals','test@himagirihospitals.com','1234567890','MULTI SPECIALITY HOSPITAL','HYDERABAD');

insert into HOSPITAL(HOSPITAL_NAME, EMAIL, PHONE_NUMBER, SPECIALIZATION, LOCATION)
VALUES('PiHealth Cancer Hospital','test@pihealthhospitals.com','1234567890','CANCER HOSPITAL','HYDERABAD');

insert into HOSPITAL(HOSPITAL_NAME, EMAIL, PHONE_NUMBER, SPECIALIZATION, LOCATION)
VALUES('Govt Mental Health Centre','test@pihealthhospitals.com','1234567890','Mental Hospital','HYDERABAD,Erragadda');


insert into DOCTOR_DETAILS(DOCTOR_NAME, EMAIL, PHONE_NUMBER, SPECIALIZATION, LOCATION, HOSPITAL_ID)
VALUES('A.Venugopal','test@pihealthhospitals.com','1234567890','Clinical Director & HOD, Senior Consultant  Medical Oncologist and Hemato-Oncologist','HYDERABAD',2);

insert into DOCTOR_DETAILS(DOCTOR_NAME, EMAIL, PHONE_NUMBER, SPECIALIZATION, LOCATION,HOSPITAL_ID)
VALUES('V.Sahiti','test@himagirihospitals.com','1234567890','Consultant Ophthalmologist','HYDERABAD',1);

insert into CUSTOMER_FOLLOWUP_NOTIFICATION (CUSTOMER_ID,DOCTOR_ID,FOLLOW_UP_DATE)
VALUES (1, 1, DATEADD('DAY', 5, CURRENT_TIMESTAMP));

insert into CUSTOMER_FOLLOWUP_NOTIFICATION (CUSTOMER_ID,DOCTOR_ID,FOLLOW_UP_DATE)
VALUES (2, 2, DATEADD('DAY', 4, CURRENT_TIMESTAMP));